services:
    pihole:
        image: pihole/pihole:latest
        container_name: pihole
        restart: always
        ports:
            - "53:53/tcp"
            - "192.168.178.61:53:53/udp"
            - "8081:80"
        environment:
            - TZ=Europe/Berlin
            - FTLCONF_dns_upstreams=194.25.0.68;194.25.0.52
            - FTLCONF_dns_hosts=192.168.178.1 fritz.box;192.168.178.61 pihole.smart.home;192.168.178.61 dashboard.smart.home;192.168.178.61 grafana.smart.home;192.168.178.61 nextcloud.smart.home;192.168.178.61 portainer.smart.home;192.168.178.61 alloy.smart.home;192.168.178.61 trivy.smart.home
            - FTLCONF_dns_listeningMode=ALL
        volumes:
            - "/home/pi/etc-pihole/:/etc/pihole/"
        networks:
            - traefik_net
        dns:
            - 194.25.0.68
            - 194.25.0.52
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.pihole.entrypoints=http"
            - "traefik.http.routers.pihole.rule=Host(`pihole.smart.home`)"
            - "traefik.docker.network=traefik_net"
            - "traefik.http.services.pihole.loadbalancer.server.port=80"

networks:
    traefik_net:
        external: true
