version: "3"

services:
    pihole:
        image: pihole/pihole:latest
        container_name: pihole
        restart: always
        ports:
            - "53:53/tcp"
            - "53:53/udp"
        environment:
            - TZ=Europe/Berlin
            - DNS1=194.25.0.68
            - DNS2=194.25.0.52
        volumes:
            - '/home/pi/etc-pihole/:/etc/pihole/'
            - '/home/pi/etc-dnsmasq.d/:/etc/dnsmasq.d/'
        networks:
            - traefik_net
        dns:
            - 127.0.0.1
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.pihole.entrypoints=http"
            - "traefik.http.routers.pihole.rule=Host(`pihole.smart.home`)"
            - "traefik.docker.network=traefik_net"
            - "traefik.http.services.pihole.loadbalancer.server.port=80"

networks:
    traefik_net:
        external: true

