{
 "title": "Logs",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Container",
    "label": "Container",
    "query": {}
   },
   {
    "name": "JournalServices",
    "label": "Journal services",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Journal logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Journal logs",
     "type": "logs",
     "gridPos": { "h": 18, "w": 24, "x": 0, "y": 1 },
     "targets": [
      {
       "direction": "backward",
       "expr": "{component=\"loki.source.journal\", unit=~\"$JournalServices\"} |= ``"
      }
     ]
    }
   ]
  },
  {
   "title": "Container logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Container logs",
     "type": "logs",
     "gridPos": { "h": 17, "w": 24, "x": 0, "y": 20 },
     "targets": [
      {
       "direction": "backward",
       "expr": "{container_name=~\"$Container\"} |= ``"
      }
     ]
    }
   ]
  },
  {
   "title": "Nextcloud backup logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Nextcloud backup logs",
     "type": "logs",
     "gridPos": { "h": 16, "w": 24, "x": 0, "y": 73 },
     "targets": [
      {
       "direction": "backward",
       "expr": "{filename=\"/var/log/nextcloud.log\"} |= ``"
      }
     ]
    }
   ]
  }
 ]
}