volumes:
    data:
    config:
    db:
    apps:
    html:

services:
    nextcloud-db:
        image: linuxserver/mariadb
        container_name: nextcloud-db
        networks:
            - docker_nextcloud_network
        restart: always
        volumes:
            - /mnt/nextcloud/db:/config
        environment:
            - MYSQL_ROOT_PASSWORD=
            - MYSQL_PASSWORD=
            - MYSQL_USER=nextcloud
            - MYSQL_DATABASE=nextcloud

    nextcloud:
        image: nextcloud:latest
        container_name: nextcloud-app
        restart: always
        ports:
            - "8082:80"
        networks:
            - docker_nextcloud_network
            - traefik_net
        depends_on:
            - nextcloud-db
        volumes:
            - /mnt/nextcloud/html:/var/www/html
            - /mnt/nextcloud/apps:/var/www/html/custom_apps
            - /mnt/nextcloud/config:/var/www/html/config
            - /mnt/nextcloud/data:/var/www/html/data
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.nextcloud.entrypoints=http"
            - "traefik.http.routers.nextcloud.rule=Host(`nextcloud.smart.home`)"
            - "traefik.http.services.nextcloud.loadbalancer.server.port=8082"
            - "traefik.docker.network=traefik_net"

networks:
    traefik_net:
        external: true
    docker_nextcloud_network:
        external: true