services:
  trivy:
    image: aquasec/trivy:latest
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
    container_name: trivy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - trivy-cache:/root/.cache/
      - $REPORT_DIR/:/reports
      - /home/pi/trivy/template/:/template
    networks:
      - traefik_net

networks:
    traefik_net:
        external: true

volumes:
  trivy-cache:
