volumes:
  portainer_data:

services:
    portainer:
        image: portainer/portainer-ce:latest
        container_name: portainer
        restart: always
        ports:
            - "8000:8000"
            - "9443:9443"
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"
            - "portainer_data:/data"
        networks:
            - traefik_net
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.portainer.entrypoints=http"
            - "traefik.http.routers.portainer.rule=Host(`portainer.smart.home`)"
            - "traefik.docker.network=traefik_net"
            - "traefik.http.services.portainer.loadbalancer.server.port=8000"

networks:
    traefik_net:
        external: true